name: Create Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Poetry
        uses: ZashIn/setup-poetry@v1
        with:
          python-version: 3.12
      - name: Check code
        id: check-code
        run: poetry run poe lint
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: mo_exporter/**/*
